### ISSUE TITLE
Support for Miyoo Mini Firmware 202310271401

### ISSUE THREAD

**Issue by CytoStorm** [schmurtzm/Miyoo-Mini-easy-logotweak#10]
v3.0.4 of the LogoTweak app does not support the latest firmware for the Miyoo Mini. App says “firmware not supported.” Would love to get this working on the latest firmware again. Thanks!

**Comment by schmurtzm** [comment]
Hi, Easy Logotweak has just been updated to v3.0.5 to support the new v4 firmware.
Can you make a try and close this issue if it is OK ?

**Comment by CytoStorm** [comment]
Just tested with the V4 firmware and works perfectly! Thank you!
