### ISSUE TITLE
Instructions wrong for Onion OS

### ISSUE THREAD

**Issue by mdeguzis** [schmurtzm/Miyoo-Mini-easy-logotweak#13]
The archive link (once extracted) is as follows:

```
$ tree Easy-LogoTweak_v3.0.5
Easy-LogoTweak_v3.0.5
└── App
    └── EasyLogoTweak
        ├── advmenu
        │   ├── advmenu
        │   ├── DOUVE - The World Of Douve.mp3
        │   └── libs
        │       ├── libexpat.so.1
        │       └── libSDL-1.2.so.0
        ├── bin
        │   ├── blank
        │   ├── checkjpg

```

You do not copy the folder to the root of the SD card, rather the EasyLogTweak folder (above advmenu seen above) into the `<SD_ROOT>/Apps` folder.

**Comment by schmurtzm** [comment]
You have to extract the content of the archive to the root of the SD card (the path is right)
