### ISSUE TITLE
support for Miyoo Mini Firmware 202407211632

### ISSUE THREAD

**Issue by stepnhie** [schmurtzm/Miyoo-Mini-easy-logotweak#15]
v3.0.5 of the easy logotweak does not support the latest firmware for the Miyoo Mini v4. When loading the app says “firmware not supported.” I would love to get this working on the latest firmware. Thanks you!

**Comment by LiamHefford** [comment]
@schmurtzm In the flash_Logo.sh script, would changing the supported version for the MM to 202407211632 and trying it on my device be a recipe for disaster or not in your opinion? I'm willing to be the sacrifice to see if the tool is compatible with the new firmware, unless there is an easier way of verifying this!

**Comment by MMagTech** [comment]
> @schmurtzm In the flash_Logo.sh script, would changing the supported version for the MM to 202407211632 and trying it on my device be a recipe for disaster or not in your opinion? I'm willing to be the sacrifice to see if the tool is compatible with the new firmware, unless there is an easier way of verifying this!

Confirmed working via the method you mentioned. See linked video for confirmation.

https://drive.google.com/file/d/1PlHdVUomzOJ0S6FgvFCI_9OLbTpFMeqN/view?usp=drivesdk

**Comment by LiamHefford** [comment]
@MMagTech Brilliant, I just tried it on my own mini v4 and can also confirm it works, thanks for testing it first! I've submitted a pull request to get the change pushed to the main project.

**Comment by schmurtzm** [comment]
Thanks for the sacrifice 😄
So I will update it soon 😉

**Comment by TripleAkat** [comment]
Thanks for testing! Does work and tried v4 native resolution but got this message:  " image1.jpg doesn't have the right resolution! It should be 640x480 (VGA) "

**Comment by schmurtzm** [comment]
PR merged, thanks @LiamHefford
