### ISSUE TITLE
[request] add support for latest firmware (20221216**** and 20221224****, 20220419****)

### ISSUE THREAD

**Issue by h2ogeek** [schmurtzm/Miyoo-Mini-easy-logotweak#4]
Unfornatually, easy logo tweak does not support the latest firmware :-(  (20221216**** and 20221224****, 20220419****). Onion added support for the new firmware.

**Comment by schmurtzm** [comment]
Hi, 
This is not exactly the firmware which is not supported but the new internal chip on the new Miyoo which is not compatible anymore. We can't write on these new SPI chip for now. This new SPI chip has required a new firmware from Miyoo so all the new Miyoo Mini with firmware 20221216, 20221224 or more have the new chip and are not compatible anymore with logotweak.

There 's an experimental way made by Eggs (he create a new firmware image to flash).
For now we're still investigate to find a solution but it will require some time ;)

**Comment by h2ogeek** [comment]
Thank you for the update!
