### ISSUE TITLE
Mini+ boot logo is offset on new 20230329 firmware

### ISSUE THREAD

**Issue by tdroza** [schmurtzm/Miyoo-Mini-easy-logotweak#6]
The latest Mini+ devices are shipping with firmware `202303292051`. [This fix ](https://github.com/schmurtzm/Miyoo-Mini-easy-logotweak/commit/8ead1f67b24622422e9803614a4f1620b2b7ac63) that was applied previously for the `202303262339` needs to be applied for the new firmware.

```
if [ "$MIYOO_VERSION" -eq "202303262339" ]; then
	# Patch screen offset for the Mini+
	HexEdit $progdir/logo.img 1086 2C
	HexEdit $progdir/logo.img 1088 4C
fi
```

I've tested this myself by manually changing the version string and it works, but I suspect you want a better fix that works with both versions, or anything newer than 20230326.

**Comment by schmurtzm** [comment]
You're totally right. It's fixed. 
For now I just check if the firmware is superior to 0326 may be it will requires more subtles in the future (but the first firmware check still here as main check).
