### ISSUE TITLE
No folder.

### ISSUE THREAD

**Issue by Androxilogin** [schmurtzm/Miyoo-Mini-easy-logotweak#7]
There is no logotweak folder. When extracted, there is an EasyLogoTweak folder. When trying to run the app, it says "loading" then crashes back to the Apps menu. If renamed to logotweak, same result. 

Firmware 202303292051 
Onion

**Comment by schmurtzm** [comment]
I presume sd card system file corruption.
Suppress the files of the previous installation, make a scandisk of your sd card, download it again and copy the files again.
Do not rename the folder.

It should work.

**Comment by Androxilogin** [comment]
Corruption already? I just got this thing today. First time copying stuff to it. I'll try scandisk and see if it'll do. So the folder is supposed to be EasyLogoTweak? Everywhere is saying it should be called logotweak.

**Comment by schmurtzm** [comment]
Yes the folder name has changed since the recent v3.

If you use stock sd card it's not a surprise to have quickly corruption.

On sandisk it happens less often (it depends if you power off the console before removing the sd card and stuffs like that).

**Comment by Androxilogin** [comment]
Strangely enough, I didn't use the one it came with. I started fresh. Nevertheless, your method worked. Thanks!
